
bridges = []

[[instances]]
name = "holofuel"
id = "__holofuel"
dna_hash = "QmdRUPDZ3xoZDJj2ciCX3Wk6eRPe9z6pnZpiVHK9cu6R6K"
uri = "https://holo-host.github.io/holofuel/releases/download/v0.13.0-alpha1/holofuel.dna.json"

[[UIs]]
name = "HoloFuel"
id = "holofuel-app"
ui_bundle_hash = "Qm34abcde"
uri = "file:./holofuel-ui.zip"

[[UIs.instance_references]]
ui_handle = "holofuel"
instance_id = "__holofuel"

[[UIs]]
name = "hAppy HoloFuel"
id = "holofuel-app"
ui_bundle_hash = "Qm34abcde"
uri = "file:./happy-holofuel.zip"

[[UIs.instance_references]]
ui_handle = "happy-holofuel"
instance_id = "__holofuel"
