persistence_dir = "{{{persistenceDir}}}"

agents = []
dnas = []
instances = []

[signals]
consistency = true
trace = true

[[interfaces]]
admin = true
id = "admin interface"
instances = []
    [interfaces.driver]
    type = "websocket"
    port = {{adminPort}}

[logger]
type = "debug"
state_dump = true

[network]
type="sim1h"
dynamo_url="https://test-networking.holo-aws.org"

[passphrase_service]
type="unixsocket"
path="{{{passphraseSocket}}}"
