persistence_dir = "{{{persistenceDir}}}"

agents = []
dnas = []
instances = []

[signals]
consistency = true
trace = true

[[interfaces]]
admin = true
id = "admin interface"
instances = []
    [interfaces.driver]
    type = "websocket"
    port = {{adminPort}}

[logger]
type = "debug"
state_dump = true

[network]
{{{networkConfigStr}}}

[passphrase_service]
type="unixsocket"
path="{{{passphraseSocket}}}"
