persistence_dir = "{{{persistenceDir}}}"

agents = []
dnas = []
instances = []

[signals]
consistency = true
trace = true

[[interfaces]]
admin = true
id = "admin interface"
instances = []
    [interfaces.driver]
    type = "websocket"
    port = {{adminPort}}

[logger]
type = "debug"
state_dump = true

[network]
type="n3h"
n3h_log_level = "i"
bootstrap_nodes = []
n3h_mode = "REAL"
n3h_persistence_path = "{{{n3hPath}}}"
