
bridges = []

[[instances]]
name = "happ-store"
id = "__happ-store"
dna_hash = "QmUdYaRoNM2wfkBoEHsvqgA9Yp4gaL4xbRcJNscW5fzw5n"
uri = "https://github.com/Holo-Host/happ-store/releases/download/v0.3.0-alpha2/hApp-store.dna.json"

[[UIs]]
name = "Happ-Store"
id = "happ-store-app"
ui_bundle_hash = "Qm34abcde"
uri = "https://github.com/Holo-Host/happ-store/releases/download/v0.3.0-alpha2/happ-store-ui.zip"

[[UIs.instance_references]]
ui_handle = "happ-store"
instance_id = "__happ-store"
