# A declaration of an instance that this hApp needs to have installed.
# `name` here is just an internal name to reference the given DNA inside the rest of this bundle.
[[instances]]
name = "personas-profiles"
id = "personas-profiles"
dna_hash = "QmVQ9GBqgsgMioCtm3fPZQhDBM8m7tBKgTnD1PCxKXqRub"
# Optional, might also be retrieved from hchc via hash long-term
uri = "file:./personas-profiles.dna.json"

[[instances]]
name = "peer-chat-public"
id = "peer-chat-public"
dna_hash = "QmPDteJSXF34CygPQFVgf7XgsoDFx5Hb3mGYvhAHH7X5Qt"
uri = "file:./peer-chat.dna.json"

[[bridges]]
handle = "p-p-bridge"
caller_id = "peer-chat-public"
callee_id = "personas-profiles"


[[UIs]]
name = "peer-chat"
id = "peer-chat-ui"
ui_bundle_hash = "Qm34abcde"
# Optional, might also be retrieved from hchc via hash long-term
uri = "file:./peer-chat-ui.zip"

# "__peer-chat" is the instance identifier in this config (declared above)
# that needs to be linked to the handle "peer-chat" which is used inside
# the definitions of the peer-chat UI.  This reference creates a link for that.
# thus we could link a different implementation of peer-chat to use the same UI
[[UIs.instance_references]]
ui_handle = "peer-chat-ui"
instance_id = "peer-chat-public"

[[UIs]]
name = "identity-manager"
id = "identity-manager-ui"
ui-bundle-hash = "Qm34abcde"
# Optional, might also be retrieved from hchc via hash long-term
uri = "file:./identity-manager-ui.zip"

[[UIs.instance_references]]
ui_handle = "identity-manager-ui"
instance_id = "personas-profiles"
