[instances.storage]
path = '/Users/philipbeadle/Library/Application Support/Holoscape-default/storage/personas-profiles'
type = 'memory'

[[instances]]
agent = 'peer-chat-public-agent'
dna = 'peer-chat-public-dna'
id = 'peer-chat-public'

[instances.storage]
path = '/Users/philipbeadle/Library/Application Support/Holoscape-default/storage/peer-chat-public'
type = 'memory'

[[interfaces]]
admin = true
id = 'admin interface'
instances = []
[interfaces.driver]
port = 4435
type = 'websocket'

[[interfaces]]
id = "websocket_interface"
admin = true
[interfaces.driver]
type = "websocket"
port = 10000
[[interfaces.instances]]
id = "peer-chat-public"
[[interfaces.instances]]
id = "personas-profiles"



[[interfaces]]
admin = true
id = 'admin interface'
instances = []
[interfaces.driver]
port = 4435
type = 'websocket'

[[interfaces]]
id = "peer-chat-public-interface"
admin = true
[interfaces.driver]
type = "websocket"
port = 10000
[[interfaces.instances]]
id = "peer-chat-public"

[[interfaces]]
id = "personas-profiles-interface"
admin = true
[interfaces.driver]
type = "websocket"
port = 10001
[[interfaces.instances]]
id = "personas-profiles"
